### ISSUE TITLE
WAService.js:3 thirdScriptError fetch is not a function;at api getLocation success callback function TypeError: fetch is not a function

### ISSUE THREAD

**Issue by xxss0903** [hingsir/weapp-douban-film#3]
WAService.js:3 thirdScriptError
fetch is not a function;at api getLocation success callback function
TypeError: fetch is not a function
    at Function.success (http://265639466.appservice.open.weixin.qq.com/pages/douban/functions.js:15:9)
    at Object.success (http://265639466.appservice.open.weixin.qq.com/WAService.js:3:6898)
    at http://265639466.appservice.open.weixin.qq.com/WAService.js:4:8110
    at Object.u [as 0.8203863081994223] (http://265639466.appservice.open.weixin.qq.com/asdebug.js:1:14219)
    at i (http://265639466.appservice.open.weixin.qq.com/asdebug.js:1:13547)
    at p (http://265639466.appservice.open.weixin.qq.com/asdebug.js:1:4336)
    at http://265639466.appservice.open.weixin.qq.com/asdebug.js:1:5158

请问这个问题在哪解决？

**Comment by cenxun** [comment]
同报这个错，放到页面的onLoad事件，fetch是可以调用的，但是在functions里的方法回调中使用时undefined

**Comment by hingsir** [comment]
@xxss0903 @cenxun 当时尝鲜的时候没有文档，试了下fetch在模拟器内可用，后来证实在真机不可用（偷懒不想改了），请使用wx.request进行网络请求

**Comment by hingsir** [comment]
@xxss0903 @cenxun 另外请使用自己的百度地图apikey，我这个貌似免费配额使用完了~

**Comment by cenxun** [comment]
了解，谢谢！
